### ISSUE TITLE
Error in _uart_xfer when calling satellite_transfer()

### ISSUE THREAD

**Issue by tomaso909** [adafruit/Adafruit_CircuitPython_RockBlock#13]
I get the following error when calling satellite_transfer():

```
Talking to satellite...
Traceback (most recent call last):
  File "code.py", line 184, in <module>
  File "adafruit_rockblock.py", line 176, in satellite_transfer
  File "adafruit_rockblock.py", line 72, in _uart_xfer
  File "adafruit_rockblock.py", line 70, in <genexpr>
TypeError: 'NoneType' object is not iterable
```

It happens with the examples provided in the repo as well. I obtained the output above when running the example file rockblock_send_data.py.

The messages sometimes get sent and sometimes don't. The error always appear.

I'm using the rockblock from a feather M0 express.

**Comment by tomaso909** [comment]
Solved !

In the examples the RockBlock object is initialized as:
```
uart = board.UART()
uart.baudrate = 19200
rb = RockBlock(uart)
```
I changed the code to this one and now it works.
```
uart = busio.UART(board.TX,board.RX,baudrate=19200)
rb = RockBlock(uart)
```
So, in the feather, the UART should be created using the busio library instead of board library.

**Comment by ladyada** [comment]
this should not matter @caternuson @dhalbert those shold be identical?

**Comment by caternuson** [comment]
Yes. Should be.

@tomaso909 Is the problem repeatable?

Here's a simple way to check comms via REPL:
```pytthon
Adafruit CircuitPython 5.3.1 on 2020-07-13; Adafruit Feather M0 Express with samd21g18
>>> import board
>>> uart = board.UART()
>>> uart.baudrate = 19200
>>> uart.write(str.encode("AT+CGMI\r"))
8
>>> uart.readline()
b'AT+CGMI\r\r\n'
>>> uart.readline()
b'Iridium\r\n'
>>> uart.readline()
b'\r\n'
>>> uart.readline()
b'OK\r\n'
>>>
```

**Comment by caternuson** [comment]
Could not recreate issue. Closing due to lack of response. Can reopen if needed.
