### ISSUE TITLE
Clarification

### ISSUE THREAD

**Issue by laupdm** [adafruit/Adafruit_CircuitPython_RockBlock#14]
https://github.com/adafruit/Adafruit_CircuitPython_RockBlock/blob/477f06723edb308e86eab3303326cdd9e0f0295a/adafruit_rockblock.py#L90

Why if the buf is already None you have to clear it again? Thank you!

**Comment by caternuson** [comment]
That code allows clearing the RockBlock's MO message buffer using the following syntax in your user code:
```python
rb.data_out = None
```
This would result in the sending of the `+SBDD0` command.

Does that help?

**Comment by laupdm** [comment]
Yes, thank you!
