### ISSUE TITLE
Sending without clear view of satellites results in an error, AT command timeouts.

### ISSUE THREAD

**Issue by zunkworks** [adafruit/Adafruit_CircuitPython_RockBlock#18]
When trying to send a message without a clear view of the satellites (no network service). The _uart_xfer function generates an error because the modem has not responded within the 1 second default UART timeout. This is problematic because none of the calling functions seem to handle the error and the code using the library halts.

If the function could wait longer or the UART timeout is modified the modem will eventually return the SBDIX status. In my no-network test, it returns MO status code 32 - "No network service, unable to initiate call.". It returned the status code within 9 seconds. I'm not sure that all issues like this return in that same amount of time. 

I don't mind writing code to fix this, I'm just unsure how you'd prefer it to be handled. I've tested code where I added a while loop in _uart_xfer with a 9 second time out and that fixed my specific problem of a long timeout. But I don't think this is the best solution (I have a few others in mind).

One solution might be to follow the SparkFun_IridiumSBD_I2C_Arduino_Library which handles this problem with configurable timeouts. The AT command timeout (atTimeout) has a default value of 20 seconds . It also has a default timeout for send/receive (sendReceiveTimeout) of 300 seconds, and a default timeout for startup (startupTimeout) of 240 seconds. 

startupTimeout functionality would be best used the init before or instead of performing a reset, it would send AT and wait for a response of AT and generate an error if the timeout is exceeded.
Something like sendReceiveTimeout could be used in the function satellite_transfer which uses SBDIX
atTimeout would be appropriate for most other AT commands and would be used in _uart_xfer

The Sparkfun Arduino library also has optional callback functionality that makes the code non-blocking, which is helpful when there are long timeouts. But this might be better discussed in a separate issue.

Another solution might be to modify the UART's timeout as needed.

Another might be the use of +SBDST – Short Burst Data: Session Timeout, which could be used to explicitly set a consistent timeout that could be matched in the library or with the UART timeout, the drawback being that the status codes are then limited to <MO status> code 2 and code 17 according to the AT command reference document. Additionally this may not allow enough time for messages to actually be sent/received, especially in poor conditions.

<MO status> code 2 doesn't make sense to me as an MO status code. The AT command ref document states:
> If a +SBDI session times out (due to <timeout> or any other internal timeout being exceeded), <MO status> code 2 will be returned. If any of the other session types time out, <MO status> code 17 will be returned (Gateway not responding quickly enough (local session timeout).)

I think they meant to say <MT status> code 2 and <MO status> code 17. <MO status> code 2 is "MO message, if any, transferred successfully, but the requested Location Update was not accepted." <MT status> code 2 is "An error occurred while attempting to perform a mailbox check or receive a message from the GSS."

It's likely there are other solutions too, these are just the ones I've thought about.

Let me know what you think and I'll start working on the changes and do a PR when it's ready.

Thanks, J

**Comment by caternuson** [comment]
This happens even with the `rockblock_send_text.py` example? If not, can you provide a simple example. It seems like UART comms should continue working even without a network (satellite) connection.

**Comment by zunkworks** [comment]
I'm not sure about the example code. When there is no network service it takes several seconds for the modem to report its status. So when the modem does not send a line within the UART's default 1 second readline timeout, readline returns None. 

This is how I dealt with it when testing with a dummy load / 50ohm terminator connected to the antenna port to simulate no network availability:

    def _uart_xfer(self, cmd):
        """Send AT command and return response as tuple of lines read."""
        self._uart.reset_input_buffer()
        self._uart.write(str.encode("AT" + cmd + "\r"))
        print(">>>" + "AT" + cmd + "\r")
        resp = []
        start_time = time.monotonic()
        line = self._uart.readline()
        print("<<<" + str(line))
        resp.append(line)
        
        while not any(EOM in line for EOM in (b"OK\r\n", b"ERROR\r\n")):
            start_time = time.monotonic()
            line = self._uart.readline()
            print("<<<" + str(line))
            #instead of this while loop, the UART timeout could be set to 9 seconds. 
            #9 seconds is based on timeout measured while doing SBDIX with 
            #no network availability this may need to be adjusted to a larger value, 
            #SBDIX session timeouts due to other problems may be longer
            #this could also be a parameter for the _uart_xfer to handle 
            #timeout variations between different commands
            while (line is None) and ((time.monotonic() - start_time) < 9):
                print(time.monotonic() - start_time)
                line = self._uart.readline()
            resp.append(line)
        print( time.monotonic() - start_time)
        self._uart.reset_input_buffer()
        print("resp:::" + str(resp))
        return tuple(resp)

Unfortunately I'm unable to implement the changes needed to properly fix this (no spare time for a while), so I'm going to go ahead and close the Issue even though it's not truly resolved.

**Comment by caternuson** [comment]
If you reopen this please provide details on the exact hardware being used and the shortest possible example code that demonstrates the issue.

I can't recreate this using an Itsy Bitsy M4 and the RockBlock 9603. The UART requests return essentially instantly:
```python
Adafruit CircuitPython 6.1.0 on 2021-01-21; Adafruit ItsyBitsy M4 Express with samd51g19
>>> import board
>>> uart = board.UART()
>>> uart.baudrate = 19200
>>> from adafruit_rockblock import RockBlock
>>> rb = RockBlock(uart)
>>> rb.model
'IRIDIUM 9600 Family SBD Transceiver'
>>> rb.status
(0, 14, 0, -1, 0, 0)
>>> 
```

**Comment by zunkworks** [comment]
I was using code similar to the following:
```
data = struct.pack("i", 5)
rb.data_out = data
status = rb.satellite_transfer()
print(status)
```
rb.status was not an issue for me.

I was using a Feather M4 Express and a RockBlock 9603 with no antenna connected just a dummy load. Indoor operation or shielding the antenna may produce a similar situation where the modem can't hear the Iridium satellites.
