### ISSUE TITLE
Sleep Pin (on/off control) RockBLOCK 9603 v3.F

### ISSUE THREAD

**Issue by alexburgis** [adafruit/Adafruit_CircuitPython_RockBlock#29]
Due to supply-chain shortage, some components in RockBLOCK 9603 3.F have been replaced with alternatives. This does not adversely affect the normal operation of the device.

Because of these component changes, 3.F now includes a transistor circuit on the On/Off control pin to ensure correct power up at all supply voltages. The On/Off control pin should not be clamped below the RockBLOCK supply voltage and should be disconnected/left floating to turn on.

Potential issue:
This change has introduced an issue when interfacing directly to a 3V3 microcontroller pin while supplying the RB with 5V. The new On/Off circuitry now provides a high impedance (1Meg resistor) to the super cap voltage, equal to the supplied voltage. This may exceed the maximum IO voltage of the micro.

If the RB was supplied by 5V, the connecting device should also be 5V tolerant. If not, it is recommended to use an interfacing circuit, eg MOSFET, transistor, relay, etc. to connect to a microcontroller.

More info:

https://docs.rockblock.rock7.com/docs/power-supply#onoff-control

**Comment by tekktrik** [comment]
Is there a specific code change that will facilitate this, or would you like to add information about this change to the README?

**Comment by caternuson** [comment]
This looks like an information thing that affects the interfacing hardware. Nothing requiring a code change.

I've request clarification from Ground Control if that issue applies *only* to the SLP pin, or affects all the other MCU interface pins as well. Will update the Learn Guide based on their response.
https://learn.adafruit.com/using-the-rockblock-iridium-modem/overview

**Comment by caternuson** [comment]
Received confirmation from Ground Control that this only applies to the SLP pin.

Updated the guide with this info:
https://learn.adafruit.com/using-the-rockblock-iridium-modem/hardware#mixed-power-slash-logic-warning-on-slp-pin-3173236

This is a hardware issue, not a code issue. I don't think there are any necessary changes needed to this library.

**Comment by caternuson** [comment]
Going to close this since it's not a library issue.
