### ISSUE TITLE
Sending 0 bytes messages when receiving data

### ISSUE THREAD

**Issue by laupdm** [adafruit/Adafruit_CircuitPython_RockBlock#8]
I want to integrate the example of receiving a message on my code (https://github.com/adafruit/Adafruit_CircuitPython_RockBlock/blob/master/examples/rockblock_recv_data.py)
 
When I tried the example, I sent an hex message from the rockblock operations page, and I received it correctly, but when I went to the messages manager on the rockblock operations I got this:

![image](https://user-images.githubusercontent.com/71781837/94043934-ceed4280-fdcd-11ea-905a-dbefbb252069.png)
 
My question is, those no-payload messages that I have theoretically sent (I only tried the code for the Reception) will be always there because of something on the manner that the AT commands check for the messages ? Have I done something wrong when sending the message? 

Thank you in advance

**Comment by ladyada** [comment]
@caternuson any ideas?

**Comment by caternuson** [comment]
The receive data example code in the library is somewhat specific to the transmit data example code. Did you alter it in anyway to work with your specific payload?

**Comment by laupdm** [comment]
I only deleted some lines related with the part of the struct.unpack()... I think that it should not affect to anything, right?
This is the script that I run
![image](https://user-images.githubusercontent.com/71781837/94251237-8eeba400-ff22-11ea-8589-f88b41ed637e.png)

**Comment by caternuson** [comment]
That should be OK. Is the behavior repeatable?

The call to `satellite_transfer()` will both send (MO) and receive (MT) messages if any messages are in the respective queues. So if you had done something prior to running the above script that had placed something in the MO buffer, then it would have been sent.

**Comment by caternuson** [comment]
That's weird that it sends a blank MO message, and cost you credits, to simply check the mailbox. We didn't see that behavior while developing this library. If the MO buffer is empty, the SBDIX command should not send anything.

**Comment by laupdm** [comment]
It is weird (and expensive, from my point of view). I connected my pc with rockblock via Serial using Putty, and then sent the AT commands without executing any script of mine that could interfer (sending or receiving messages) 
![image](https://user-images.githubusercontent.com/71781837/94290747-ea398880-ff5a-11ea-8ba9-c36a5a1edce5.png)
As you can see, I only looked for satellite connection, if it can get one, with the SBDIX command, without any previous SBDWT or anything. The response that I got is [0,71,0,0,0,0] where the 71 is indicating the Mobile Originated Message Sequence Number (MOMSN), and no messages to download. 

As you can see here, what I got on the Rockblock Operations page is a 0 bytes message for 1 credit. 

![image](https://user-images.githubusercontent.com/71781837/94291610-228d9680-ff5c-11ea-900e-03bc8bcb7b7e.png)

As I said, when you are sending your own payload, it includes a "free check" and it will only cost the length of your payload. But when you try to receive a message without sending anything before, it costs you 1 credit.

**Comment by caternuson** [comment]
Try clicking the "View" button and see if you can see anything related to getting the red ! for Status.

**Comment by laupdm** [comment]
The red ! is because I put the adress to send the message to a server that I have not activated yet (I should delete it, but I think it has nothing to do with this), I also have my email adress in the delivery adresses and it is green status.
![image](https://user-images.githubusercontent.com/71781837/94295112-10622700-ff61-11ea-9288-fabc1a3341ae.png)

**Comment by caternuson** [comment]
@ladyada OK to reactivate this for a month to investigate?

**Comment by ladyada** [comment]
of course!

**Comment by caternuson** [comment]
I've recreated this issue. Even with issuing a clear buffer command:
```
AT+CSQ
+CSQ:5

OK
AT+SBDD2
0

OK
AT+SBDIX
+SBDIX: 0, 13, 0, 0, 0, 0
```

I get hit for 1 credit :(

I've sent an email to Rock7 tech support to see if they can explain.

**Comment by caternuson** [comment]
The response from Rock7 is that this is expected behavior. Here's the important bit of detail:

> any connection to the satellite will incur a fee. Whether that be a blank Mailbox Check or an MO from your modem with an actual payload.

We only tested a few simple message xfers, which is maybe why we didn't run into this behavior. Of course, this does have a significant impact on how you will design your code. I see this as meaning you can't perform a simple "check for messages" for free. It will cost you at least 1 credit.

Hope that info helps.
